### ISSUE TITLE
Practica de Calidad

### ISSUE THREAD

**Issue by FedericoVictorianoSierra** [SistemasTecTlaxiaco/practica-6-practica-de-calidad-metricas-con-testrail-equipo-promastergamer777#1]

**Comment by FedericoVictorianoSierra** [comment]
[Práctica 2 Test (Federico Victoriano Sierra).pdf](https://github.com/SistemasTecTlaxiaco/practica-6-practica-de-calidad-metricas-con-testrail-equipo-promastergamer777/files/12786320/Practica.2.Test.Federico.Victoriano.Sierra.pdf)

**Comment by Heidi-19** [comment]
[Práctica 2 Test - Heidi Lucy Bautista Sanjuan 7USC.pdf](https://github.com/SistemasTecTlaxiaco/practica-6-practica-de-calidad-metricas-con-testrail-equipo-promastergamer777/files/12786392/Practica.2.Test.-.Heidi.Lucy.Bautista.Sanjuan.7USC.pdf)

**Comment by Gregorio012** [comment]
bien, 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
